name: C/C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: apt-get
      run: sudo apt-get update
    - name: comp
      run: mkdir Tools && mkdir Tools/completion && cd Tools/completion && wget https://github.com/ArduPilot/ardupilot/raw/master/Tools/completion/completion.bash && mkdir bash && cd bash && wget https://github.com/ArduPilot/ardupilot/raw/master/Tools/completion/bash/_waf
    - name: stup
      run: mkdir Tools/environment_install && cd Tools && cd environment_install && wget https://github.com/ArduPilot/ardupilot/raw/master/Tools/environment_install/install-prereqs-ubuntu.sh && bash ./install-prereqs-ubuntu.sh -y
    - name: deploy
      run: source ~/.profile && chmod 777 ./deploy.sh && ./deploy.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: firmwares
        # A file, directory or wildcard pattern that describes what to upload
        path: deploy
